package namegenerator;
import java.util.Arrays;

public class NG_OldEnglishMale extends NameGenerator {
	public NG_OldEnglishMale() {
		String demoVocals[] = { "y", "e", "ey", "ie", "e", "a", "o", "a", "o", "a", "o", "ay", "e", "y", "o", "a", "e", "a", "e", "a", "i", "e", "i", "o", "e", "a", "e", "a", "i", "e", "y", "e", "e", "e", "a", "e", "e", "y", "e", "e", "o", "e", "i", "e", "o", "i", "o", "y", "i", "oo", "i", "e", "a", "a", "e", "i", "e", "ei", "ie", "i", "i", "a", "ee", "a", "u", "e", "u", "o", "a", "o", "a", "o", "e", "a", "a", "a", "e", "a", "a", "o", "ai", "a", "ea", "a", "i", "a", "o", "a", "i", "a", "a", "a", "a", "e", "a", "e", "ay", "e", "aye", "ea", "o", "i", "o", "e", "a", "ie", "e", "e", "e", "e", "i", "e", "i", "e", "o", "i", "o", "i", "oo", "ai", "oo", "a", "e", "a", "o", "au", "e", "a", "o", "a", "o", "ei", "e", "e", "e", "e", "i", "o", "i", "oo", "i", "o", "i", "i", "o", "oo", "y", "e", "a", "i", "a", "e", "a", "o", "ea", "e", "i", "e", "i", "e", "y", "i", "ou", "i", "o", "i", "a", "o", "a", "o", "o", "a", "i", "o", "o", "o", "o", "i", "o", "oo", "ay", "o", "a", "o", "a", "o", "o", "o", "a", "a", "a", "e", "a", "o", "a", "o", "e", "o", "o", "o", "e", "e", "o", "a", "a", "i", "a", "a", "o", "a", "o", "a", "ei", "a", "e", "a", "a", "a", "a", "a", "e", "a", "o", "a", "o", "a", "e", "a", "i", "ay", "u", "ay", "o", "ea", "i", "e", "o", "e", "i", "e", "e", "i", "e", "e", "e", "a", "ey", "o", "i", "i", "o", "o", "e", "o", "e", "o", "a", "o", "o", "ou", "o", "e", "o", "o", "o", "u", "ya", "u", "o", "u", "o", "u", "o", "u", "a", "o", "a", "i", "a", "o", "a", "o", "au", "e", "a", "o", "o", "ea", "e", "ea", "ea", "oo", "e", "e", "e", "e", "o", "e", "e", "e", "e", "oo", "o", "e", "o", "e", "o", "e", "ou", "e", "a", "i", "a", "ie", "a", "o", "a", "a", "o", "o", "a", "o", "a", "o", "ou", "y", "e", "a", "a", "a", "a", "a", "u", "e", "y", "a", "e", "o", "u", "o", "o", "u", "o", "u", "a", "i", "o", "o", "e", "a", "e", "i", "o", "y", "o", "o", "e", "i", "o", "oo", "ai", "e", "ai", "i", "a", "a", "e", "a", "e", "a", "y", "a", "u", "a", "u", "a", "e", "e", "e", "o", "e", "oo", "e", "o", "ea", "o", "ee", "e", "i", "i", "ie", "i", "a", "i", "e", "i", "i", "e", "i", "a", "i", "o", "y", "a", "y", "a", "y", "a", "e", "ey", "e", };
		String demoStartConsonants[] = { "aldr", "aldw", "alg", "arl", "ashl", "ath", "axt", "b", "b", "bl", "br", "br", "br", "br", "b", "b", "b", "b", "c", "c", "ch", "ch", "cr", "cr", "d", "d", "d", "d", "d", "d", "d", "dr", "dw", "earl", "edb", "edl", "eg", "eldr", "elsd", "elv", "elw", "elw", "erw", "ev", "f", "f", "f", "f", "f", "f", "fr", "fr", "f", "f", "gl", "g", "g", "gr", "gr", "gr", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "j", "j", "k", "k", "k", "k", "k", "k", "k", "k", "k", "k", "k", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "l", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "n", "n", "n", "n", "n", "n", "n", "ogl", "ordw", "orf", "orm", "orm", "osm", "osm", "oxf", "oxt", "p", "p", "p", "p", "p", "p", "p", "pr", "pr", "pr", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "r", "s", "s", "s", "s", "s", "s", "sc", "s", "s", "s", "s", "s", "sh", "sh", "sh", "sh", "sh", "sh", "sn", "s", "s", "s", "st", "st", "st", "st", "st", "st", "st", "st", "str", "str", "str", "s", "t", "t", "t", "t", "t", "th", "th", "th", "th", "th", "th", "th", "th", "t", "t", "tr", "tr", "tr", "tw", "ud", "ulfr", "unw", "upt", "upw", "v", "v", "v", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "w", "wh", "wh", "wh", "wh", "wh", "w", "w", "w", "w", "w", "w", "w", "w", "w", "yal", "yardl", "york", "yul", "z", };
		String demoEndConsonants[] = { "n", "r", "gh", "lst", "n", "n", "rt", "n", "xt", "n", "tt", "f", "rd", "ld", "r", "lv", "rt", "dw", "ck", "tw", "n", "mw", "ll", "lb", "rt", "ll", "n", "lw", "n", "mpst", "r", "rw", "rd", "v", "r", "d", "n", "nn", "n", "rt", "n", "rt", "n", "c", "n", "n", "d", "n", "r", "rd", "nw", "ck", "rnl", "gh", "ld", "ng", "rth", "m", "n", "ll", "r", "lt", "n", "dst", "dd", "rd", "m", "r", "nth", "m", "sh", "m", "dd", "n", "g", "lst", "d", "m", "lt", "mpt", "n", "rdw", "n", "rgr", "rl", "n", "sl", "tt", "v", "n", "d", "n", "s", "thc", "ll", "s", "lm", "s", "m", "s", "ff", "rs", "mp", "ndr", "ck", "nr", "ck", "nt", "n", "ngst", "n", "rkw", "d", "br", "k", "nc", "l", "ngw", "rth", "nc", "l", "wf", "rd", "ws", "n", "gh", "st", "r", "v", "rt", "nf", "rd", "nw", "d", "tt", "n", "v", "ngst", "ckw", "d", "nd", "ll", "nn", "ng", "rd", "n", "rl", "w", "d", "dw", "n", "rr", "ll", "rv", "n", "lb", "rn", "lf", "rd", "ll", "rd", "rl", "nd", "rt", "n", "sh", "cks", "n", "rth", "rv", "rv", "n", "rw", "d", "rd", "n", "nd", "r", "nd", "rd", "n", "ck", "rd", "lm", "r", "tt", "n", "xt", "n", "lt", "n", "ll", "ck", "nt", "sc", "tt", "db", "dcl", "ff", "dcl", "df", "rd", "dn", "r", "l", "gh", "msd", "n", "n", "ld", "nd", "l", "nd", "ll", "nd", "lph", "ns", "m", "v", "n", "v", "ng", "b", "rn", "n", "ld", "d", "ng", "df", "rd", "g", "n", "m", "ngt", "nfr", "d", "nsh", "w", "n", "ld", "dg", "st", "n", "ch", "st", "ckw", "ll", "n", "ld", "ns", "n", "tl", "w", "ll", "ws", "n", "xb", "d", "rd", "ff", "rd", "mf", "rd", "shf", "rd", "tl", "ff", "rd", "l", "sb", "lt", "n", "nb", "rn", "nd", "rs", "x", "n", "tt", "b", "rt", "b", "br", "k", "g", "r", "ld", "n", "ph", "rd", "rb", "rw", "d", "wd", "n", "m", "rs", "m", "rv", "thw", "ll", "nd", "sh", "nf", "ld", "nf", "rd", "nh", "rr", "ckt", "n", "tf", "rd", "tt", "n", "d", "k", "s", "nn", "r", "rr", "nt", "t", "m", "nn", "s", "tch", "r", "rm", "nd", "rnt", "n", "rl", "w", "rst", "n", "lf", "rd", "wns", "nd", "nt", "r", "pp", "wbr", "f", "rd", "lf", "d", "n", "n", "d", "l", "nn", "nwr", "ght", "k", "f", "k", "m", "lw", "n", "rb", "rt", "rm", "nd", "v", "bst", "r", "ntw", "rth", "stbr", "k", "st", "n", "t", "n", "l", "r", "tc", "tf", "ld", "ckh", "m", "lk", "s", "ll", "nch", "st", "st", "n", "tt", "n", "nd", "m", "ndh", "m", "st", "n", };
		String demofemaleEnd[] = { "idge", "arclay", "adley", "omley", "uckley", "urke", "urley", "ewe", "enley", "eux", "irley", "ane", "yne", "one", "eme", "adley", "agley", "on", "eave", "ote", "edley", "untley", "uxley", "on", "on", "enley", "enley", "insey", "irkley", "yne", "ot", "ane", "angley", "ot", "on", "inley", "on", "ocke", "acy", "arley", "orley", "ille", "yle", "esby", "enley", "ice", "esley", "orne", "iffe", "amsay", "ansley", "er", "awley", "ald", "illy", "on", "eway", "idgley", "idley", "isley", "er", "ockley", "edge", "owley", "ury", "edge", "utley", "yle", "yley", "ury", "on", "orne", "aley", "andy", "elley", "orne", "et", "ille", "ope", "anley", "owe", "eddie", "on", "orne", "ornley", "orpe", "idge", "ane", "ite", "ield", "an", "alby", "on", "arley", "erly", "elby", "estby", "itby", "ombe", "oughby", "er", "ale", };
		String nameInstructions[] = { "cf", "cvd", "cvd", "cv", "cvd", "cvdvd", "cvd", "cf", "cvdvd", "cvdvd", "cf", "cv", "cvd", "cf", "cf", "cf", "cf", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cf", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cf", "cvdvd", "cvdvdf", "cvdvd", "cvdvd", "c", "cvd", "cvd", "cvdvd", "cvd", "cvd", "cv", "cvd", "cvd", "cvd", "cvdvd", "cvf", "cf", "cvdvd", "cvdvd", "cvdvd", "cvd", "cvf", "cvdvd", "cvdvd", "cvdvd", "cvdf", "cvdvd", "cvdvd", "cvf", "cvdvd", "cvdvd", "cvdvd", "cf", "cf", "cvd", "cvdvd", "cvdvdf", "cvdvd", "cvdvd", "cvdf", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvd", "cvdf", "cf", "cvdvd", "cvdvd", "cf", "cf", "cvdvdf", "cvdvdf", "cvd", "cvdvd", "cf", "cf", "cvdvd", "cvdvd", "cvdvd", "cf", "cf", "cvdvd", "cf", "cvdvd", "cvdvdf", "cf", "cf", "cvdvd", "cvdvdf", "cvdvd", "cvdvd", "cvd", "cvdvd", "cvdvdf", "cvdvd", "cf", "cvdvd", "cvdvd", "cvdvdf", "cf", "cvdvd", "cvdvd", "cf", "cvdvd", "cvdvd", "cf", "cvdvd", "cvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cf", "cvdvd", "cvd", "cvdvd", "cvd", "cvdf", "cvdvd", "cvdvd", "cf", "cf", "cv", "cvd", "cvd", "cvd", "cvd", "cvd", "cvd", "cvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cf", "cvdvd", "cvdf", "cvdvd", "cf", "cvdf", "cvdvd", "cvdf", "cvdvd", "cvdvd", "cvdvd", "cf", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cf", "cvdvd", "cvdvd", "cvdvdf", "cf", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdvdf", "cvf", "cvdvdf", "cvdvd", "cvdvd", "cvdvd", "cvdf", "cf", "cf", "cf", "cvdvd", "cvdvdf", "cf", "cvdvd", "cvdvd", "cvdvd", "cvdf", "cvdvd", "cf", "cvdvd", "cvdf", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdf", "cf", "cf", "cf", "cvdvd", "cvdvdf", "cvdvd", "cvdvd", "cvdvdf", "cvdvd", "cvd", "cvdvd", "cvdf", "cvdvd", "cvf", "cvdvd", "cf", "cvdvd", "cf", "cvdvd", "cvdf", "cvdvd", "cvdvd", "cvdvdf", "cvdvdf", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdf", "cf", "cvd", "cvdvd", "cf", "cvdvd", "cvdvd", "cvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cf", "cvdvdf", "cvdvd", "cvdvd", "cf", "cf", "cvdvd", "cf", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvd", "cvdf", "cvdvd", "cvd", "cvd", "cvd", "cvd", "cvd", "cvd", "cf", "cvd", "cvdvd", "cvf", "cvdvdf", "cvdvdf", "cf", "cvdvd", "cvdvdf", "cf", "cvdvd", "cvdf", "cvdvd", "cf", "cvdvd", "cvdvd", "cf", "cvdvd", "cvdvd", "cvdvd", "cf", "cvdf", "cvdvd", "cvdvd", "cvdvd", "cvdf", "cvdvdf", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cvdvd", "cv", "cv", "c", "cv", "cf", };


		this.vocals.addAll(Arrays.asList(demoVocals));
		this.startConsonants.addAll(Arrays.asList(demoStartConsonants));
		this.endConsonants.addAll(Arrays.asList(demoEndConsonants));
		this.nameInstructions.addAll(Arrays.asList(nameInstructions));
		this.femaleEnd.addAll(Arrays.asList(demofemaleEnd));
	}
}
