package roleplay.namegenerator;
import java.util.Arrays;

public class NG_ElvishFemale extends NameGenerator {
	public NG_ElvishFemale() {
		String demoVocals[] = { "ieye", "e", "a", "a", "a", "a", "a", "a", "e",
				"o", "i", "oe", "ae", "ue", "a", "a", "a", "ei", "a", "y", "a",
				"a", "ie", "a", "au", "a", "a", "a", "u", "y", "o", "a", "ae",
				"ae", "a", "a", "au", "ae", "a", "a", "a", "i", "o", "i", "i",
				"iy", "a", "a", "a", "ae", "a", "a", "a", "e", "i", "e", "eu",
				"u", "ae", "a", "a", "a", "a", "i", "o", "a", "a", "o", "a",
				"a", "e", "a", "a", "au", "a", "ae", "ie", "i", "au", "i", "i",
				"a", "ae", "ae", "a", "e", "a", "i", "e", "y", "y", "aa", "a",
				"a", "a", "a", "a", "a", "a", "a", "a", "a", "e", "o", "u",
				"y", "i", "y", "y", "a", "i", "i", "a", "o", "i", "a", "i",
				"i", "e", "a", "a", "a", "au", "i", "e", "y", "i", "i", "a",
				"a", "ay", "e", "ei", "e", "ii", "i", "eo", "y", "aa", "a",
				"ae", "au", "a", "ei", "i", "a", "o", "y", "ae", "aa", "e",
				"ae", "ae", "a", "a", "a", "a", "a", "a", "e", "e", "e", "e",
				"e", "ia", "e", "e", "i", "a", "o", "o", "y", "ue", "y", "y",
				"y", "ae", "a", "a", "y", "a", "e", "a", "au", "u", "ue", "uo",
				"u", "y", "y", "ue", "a", "a", "e", "ui", "uo", "ua", "ae",
				"ae", "a", "e", "oa", "u", "ae", "a", "a", "a", "e", "e", "e",
				"a", "a", "o", "a", "a", "a", "a", "a", "a", "a", "a", "e",
				"e", "ia", "ae", "ia", "ae", "o", "ya", "ya", "y", "i", "i",
				"a", "o", "o", "o", "u", "a", "y", "u", "y", "y", "y", "a",
				"a", "a", "a", "a", "a", "a", "a", "a", "y", "e", "a", "e",
				"a", "a", "a", "a", "a", "i", "o", "i", "i", "i", "e", "ae",
				"a", "a", "e", "au", "e", "e", "u", "e", "e", "ia", "i", "o",
				"ii", "e", "a", "i", "a", "a", "a", "ui", "e", "o", };
		String demoStartConsonants[] = { "ael", "a", "ael", "aer", "ahr",
				"ahr", "ahsk", "ajh", "al", "al", "al", "al", "al", "all",
				"all", "all", "all", "alm", "al", "alv", "al", "al", "am",
				"am", "amk", "aml", "amn", "an", "an", "an", "anh", "an", "ar",
				"ar", "arc", "ar", "arl", "arn", "art", "ash", "aub", "a", "a",
				"ax", "ayaeql", "az", "bh", "bl", "b", "br", "c", "c", "c",
				"ch", "ch", "ch", "ch", "ch", "ch", "c", "c", "cl", "csh", "d",
				"d", "d", "d", "d", "d", "d", "d", "d", "d", "d", "eall", "ec",
				"edr", "el", "el", "el", "eldr", "el", "ell", "ell", "el",
				"el", "elv", "emv", "en", "esh", "ess", "est", "f", "f", "fh",
				"f", "f", "f", "f", "fr", "g", "g", "g", "g", "gh", "gl", "gw",
				"gw", "g", "h", "h", "h", "h", "h", "h", "h", "h", "h", "hh",
				"h", "h", "h", "iah", "ial", "ik", "ild", "ilm", "il", "il",
				"imd", "im", "imm", "imr", "imr", "inn", "ioel", "irh", "isc",
				"ithr", "it", "it", "j", "j", "jh", "jh", "jh", "jh", "jh",
				"ils", "il", "imm", "is", "k", "k", "k", "k", "k", "kh", "k",
				"k", "l", "l", "l", "l", "l", "l", "l", "ll", "l", "l", "m",
				"m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m",
				"m", "m", "m", "ml", "mn", "m", "m", "m", "m", "m", "m", "n",
				"n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n",
				"och", "ol", "ph", "ph", "ph", "ph", "ph", "p", "p", "q", "q",
				"r", "r", "r", "r", "r", "r", "r", "r", "s", "s", "s", "s",
				"s", "sch", "s", "s", "s", "sh", "sh", "sh", "sh", "sh", "sh",
				"sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh",
				"sh", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s", "s",
				"t", "t", "t", "t", "t", "t", "t", "t", "t", "t", "th", "th",
				"th", "th", "thr", "t", "t", "t", "ts", "ul", "urm", "usch",
				"v", "v", "v", "v", "v", "v", "v", "v", "v", "w", "x", "yaer",
				"yal", "yathl", "ygh", "ygr", "ynsh", "yrl", "yrn", "yrthr",
				"ysm", "yth", "yulm", "zh", "z", };
		String demoEndConsonants[] = { "nd", "h", "l", "gl", "v", "r", "r",
				"th", "v", "r", "nd", "r", "r", "h", "r", "ll", "l", "d", "m",
				"r", "r", "r", "thsw", "nn", "l", "r", "rth", "l", "r", "l",
				"n", "ls", "ndr", "s", "chl", "m", "l", "vr", "r", "d", "r",
				"n", "r", "tr", "s", "l", "mb", "lsh", "l", "r", "n", "n", "r",
				"f", "nd", "r", "r", "jh", "r", "n", "r", "n", "l", "rt", "r",
				"l", "r", "l", "ld", "nc", "l", "rr", "mst", "rz", "l", "nn",
				"ll", "l", "c", "l", "l", "l", "l", "n", "m", "l", "r", "m",
				"l", "l", "q", "c", "l", "r", "th", "l", "z", "m", "v", "nd",
				"l", "n", "mr", "v", "r", "lf", "rr", "vr", "l", "sh", "thr",
				"p", "l", "nth", "th", "mt", "r", "rl", "zz", "l", "l", "mr",
				"r", "r", "s", "l", "sh", "l", "r", "k", "lr", "r", "r", "rt",
				"l", "r", "th", "r", "l", "r", "rl", "st", "dr", "rgw", "r",
				"gg", "rl", "l", "l", "r", "v", "k", "m", "r", "nal", "th",
				"nthl", "m", "l", "v", "sh", "l", "ll", "v", "nt", "l", "ng",
				"rl", "m", "j", "r", "th", "n", "nm", "l", "k", "r", "ld", "l",
				"d", "wm", "l", "l", "l", "lh", "nd", "l", "n", "r", "l", "v",
				"l", "v", "ll", "s", "nn", "f", "l", "rs", "skl", "h", "mr",
				"st", "nn", "r", "v", "k", "l", "l", "n", "l", "l", "m", "ras",
				"n", "h", "r", "r", "l", "l", "n", "s", "t", "l", "r", "sh",
				"l", "rvensh", "l", "l", "laeth", "n", "l", "l", "th", "rr",
				"st", "ns", "nterfl", "w", "lth", "n", "r", "nt", };
		String demofemaleEnd[] = { "eva", "elrue", "ynthi", "ilaya", "aaria",
				"endue", "ala", "anda", "ossa", "is", "uthshaee", "ara",
				"athla", "annia", "isa", "alla", "ynna", "ara", "an", "ele",
				"alee", "yndra", "ara", "anthae", "issra", "uil", "estria",
				"arae", "arzee", "in", "ern", "an", "ushnee", "avae", "ena",
				"imnda", "yna", "arra", "in", "emmi", "eira", "uluua", "urae",
				"ilya", "une", "iah", "aelea", "ana", "urie", "indra", "ynna",
				"el", "adra", "ath", "arda", "elle", "ianna", "andra", "ylla",
				"en", "yl", "ire", "ynn", "alaia", "ine", "arshee", "yra",
				"athlue", "athlue", "athlue", "iyra", "andra", "arla", "ilya",
				"yrl", "is", "ele", "alue", "il", "asha", "atha", "etha",
				"ian", "ain", "en", "ora", "uil", "ele", "as", "esra", "erae",
				"er", "anni", "yn", "ala", "yat", "el", "auria", "aerae",
				"essca", "ira", "adh", "ylia", "ah", "anna", "ynnii", "yr",
				"estri", "edha", "ija", "athra", "aema", "ama", "aema",
				"aestra", "itia", "ara", "artha", "ora", "one", "uethae", "is",
				"alae", "antha", "eshia", "yntra", "adia", "ana", "yrra",
				"ace", "ael", "anthe", "arthree", "yll", "il", "ena", "al",
				"ira", "ythra", "ireae", "ylra", "astra", "ardra", "er", "ass",
				"andra", "ithe", "ilsraa", "el", "ana", "anthe", "el", "ala",
				"essa", "erla", "ara", "yllia", "aera", "eal", "aela", "ora",
				"erdya", "une", "aethee", "iar", "atha", "uth", "yl", "elei",
				"el", "iira", "yrra", "alya", "ith", "aela", "uthiia", "iona",
				"issa", "ainn", "ira", "arue", "yl", "eth", "iel", "ara",
				"ale", "is", "uvae", "ais", "an", "ara", "aela", "aerla",
				"iani", "ys", "iasha", "ambra", "iitha", "alee", "anthee",
				"eene", "ys", "ala", "eth", "is", "ala", "aathria", "yss",
				"aera", "erl", "yni", "orna", "ara", "yrra", "ollae", "aas",
				"emba", "ara", "iisa", "auntha", "iain", "estrae", "ara",
				"avia", "ubrae", "yllae", "ihn", "ida", "aala", "iandi",
				"arya", "imae", "irye", "anna", "ussa", "el", "oon", "ana",
				"antha", "endra", "eira", "ar", "yrria", "aera", "edra", "era",
				"ar", "ar", "ulree", "el", "el", "yrr", "ain", "iania", "ora",
				"asta", "ava", "ylmae", "ar", "yndra", "orha", "une", "iis",
				"enya", "ari", "aedra", "ashta", "ila", "indra", "ara", "ora",
				"issa", "yani", "aera", "il", "ola", "alia", "eatha", "atha",
				"iara", "aru", "arra", "esse", "icca", "ymna", "ice", "indra",
				"ashti", "yl", "atha", "il", "ona", "ele", "ola", "er", "arra",
				"ene", "ilue", "anae", "ilra", "inne", "el", "issa", "eha",
				"ethra", "yrlda", "arra", "anda", "el", "astria", };
		String nameInstructions[] = { "cvf", "cf", "cf", "cf", "cvdf", "cf",
				"cvdf", "cvdf", "cvdf", "cvf", "cvf", "cvdf", "cvdf", "cf",
				"cf", "cvdf", "cf", "cvdf", "cvdf", "cvdf", "cvdf", "cf", "cf",
				"cvdf", "cf", "cvdf", "cf", "cvdf", "cf", "cvdf", "cvf",
				"cvdf", "cvf", "cf", "cvf", "cvdf", "cvf", "cf", "cf", "cf",
				"cvdvdf", "cf", "cf", "cf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvdvdf", "cvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cvdvdf", "cvdvdf", "cvf",
				"cvdf", "cvdf", "cvdvdf", "cf", "cvdf", "cf", "cf", "cf",
				"cvdvdf", "cvdf", "cvdf", "cvf", "cf", "cvdf", "cvf", "cvdf",
				"cvdf", "cf", "cf", "cf", "cvdf", "cvdf", "cvf", "cf",
				"cvdvdf", "cvdf", "cvdvdf", "cvdf", "cvf", "cf", "cvdf",
				"cvdvdf", "cvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvdf", "cvf", "cvdvdf", "cvdf", "cf", "cvf", "cvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdvdf",
				"cvdvdf", "cvdvdf", "cvdf", "cf", "cvdf", "cvdf", "cvdf", "cf",
				"cf", "cf", "cvdf", "cf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvf", "cvdf", "cf", "cvdvdf", "cf", "cvf", "cvf", "cf", "cvf",
				"cf", "cf", "cvf", "cvf", "cvdf", "cvdf", "cvdf", "cvf",
				"cvdf", "cvdf", "cvf", "cvdvdf", "cvdf", "cvdf", "cvf", "cvdf",
				"cvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvf", "cvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdvdf",
				"cvdvdf", "cvdf", "cvdf", "cvf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvdf", "cvf", "cvdf", "cvdvdf", "cvdvdf", "cvdf",
				"cvdf", "cvdf", "cvdf", "cf", "cvdf", "cvdvdf", "cvdf", "cvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cf", "cvdvdf", "cvdvdf", "cf",
				"cvdf", "cvdf", "cvf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvf", "cvdf", "cvdf", "cvdf", "cf", "cf", "cvdf",
				"cf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvf",
				"cf", "cf", "cvdf", "cvf", "cvdf", "cvdf", "cf", "cf", "cvf",
				"cvdf", "cvdf", "cvf", "cvdvdf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvdvdf", "cvdf", "cvdf", "cvf", "cvf", "cvdvdf",
				"cvdvdf", "cvf", "cvf", "cvf", "cvdvdf", "cvdvdf", "cvdf",
				"cvf", "cvdf", "cvdvdf", "cf", "cvdvdf", "cf", "cvdf", "cvdf",
				"cvdf", "cvf", "cvdf", "cvdf", "cvdvdf", "cvdf", "cvdf",
				"cvdf", "cvdvdf", "cvdvdf", "cvdf", "cvdf", "cvdvdf", "cvf",
				"cvdvdf", "cvdf", "cvf", "cvdf", "cvdf", "cf", "cvdf", "cf",
				"cf", "cvdvdf", "cvdf", "cf", "cvdvdf", "cvdf", "cvdvdf",
				"cvdf", "cvdf", "cvdf", "cvdvdf", "cvdf", "cvf", "cvdf", "cf",
				"cvf", "cvf", "cvf", "cf", "cf", "cvf", "cf", "cf", "cf",
				"cvdvdf", "cvf", };

		this.vocals.addAll(Arrays.asList(demoVocals));
		this.startConsonants.addAll(Arrays.asList(demoStartConsonants));
		this.endConsonants.addAll(Arrays.asList(demoEndConsonants));
		this.nameInstructions.addAll(Arrays.asList(nameInstructions));
		this.femaleEnd.addAll(Arrays.asList(demofemaleEnd));
	}
}
