package roleplay.namegenerator;
import java.util.Arrays;

public class NG_ElvishMale extends NameGenerator {
	public NG_ElvishMale() {
		String demoVocals[] = { "a", "a", "o", "e", "e", "i", "e", "a", "a",
				"a", "e", "a", "y", "o", "i", "a", "o", "i", "a", "a", "ae",
				"a", "a", "ui", "ae", "a", "a", "i", "i", "a", "au", "a", "a",
				"ou", "ae", "e", "ae", "i", "e", "a", "e", "e", "e", "e", "y",
				"i", "ia", "y", "ia", "a", "i", "u", "o", "a", "e", "aa", "a",
				"a", "e", "o", "a", "y", "u", "u", "u", "o", "o", "o", "o",
				"o", "y", "y", "a", "a", "a", "a", "a", "a", "a", "a", "a",
				"i", "e", "e", "e", "a", "oe", "i", "i", "a", "ui", "u", "u",
				"o", "y", "y", "a", "e", "au", "ae", "a", "a", "a", "a", "au",
				"e", "a", "e", "e", "iea", "a", "i", "i", "a", "i", "o", "i",
				"o", "a", "a", "a", "y", "e", "i", "a", "a", "o", "o", "a",
				"e", "i", "i", "aa", "ae", "ae", "ae", "a", "a", "ao", "e",
				"e", "ao", "o", "i", "a", "i", "e", "i", "e", "a", "i", "o",
				"y", "ae", "ae", "a", "ae", "a", "a", "a", "a", "a", "a", "a",
				"a", "y", "ii", "i", "a", "o", "a", "o", "o", "a", "aa", "a",
				"ae", "a", "a", "a", "a", "a", "a", "a", "ei", "a", "a", "o",
				"a", "ae", "a", "a", "a", "a", "a", "a", "i", "a", "o", "o",
				"u", "i", "a", "ia", "i", "i", "i", "i", "a", "i", "i", "u",
				"y", "a", "ia", "e", "ai", "i", "a", "i", "a", "a", "a", "a",
				"ao", "a", "a", "aa", "ae", "a", "a", "u", "o", "o", "o", "i",
				"o", "i", "u", "a", "a", "ae", "a", "a", "e", "e", "e", "e",
				"e", "e", "e", "e", "aa", "i", "a", "a", "i", "ii", "i", "uu",
				"y", "i", "i", "e", "iyu", "a", "o", "o", "i", "o", "uo", "u",
				"u", "y", "y", "ae", "a", "a", "a", "a", "a", "o", "a", "a",
				"a", "ae", "eayo", "a", "eo", "o", "o", "ia", "e", "e", "o",
				"o", "ui", "u", "u", "y", "y", "y", "a", "a", "ae", "e", "ae",
				"a", "ae", "ai", "a", "a", "a", "i", "a", "e", "e", "a", "e",
				"a", "e", "e", "e", "e", "ae", "i", "a", "ii", "ae", "ii", "i",
				"i", "a", "o", "o", "o", "o", "a", "o", "o", "o", "o", "y",
				"y", "y", "y", "i", "y", "a", "a", "ae", "y", "ae", "y", "a",
				"ae", "a", "a", "e", "ae", "e", "ae", "e", "e", "e", "e", "e",
				"a", "a", "ie", "i", "i", "a", "o", "o", "e", "u", "yaa", "y",
				"y", "o", "a", "i", "i", "i", "a", "a", "a", "a", "a", "e",
				"ae", "ae", "o", "ae", "ae", "a", "o", "au", "o", "ae", "a",
				"a", "i", "eu", "u", "y", "y", "a", "y", "i", "ua", "u", "ae",
				"a", "ai", "a", "i", "a", "a", "au", "ae", "au", "o", "au",
				"e", "e", "u", "e", "e", "e", "e", "e", "a", "a", "e", "a",
				"e", "i", "o", "o", "i", "i", "i", "ua", "o", "o", "o", "i",
				"u", "ue", "u", "u", "a", "u", "u", "u", "y", "y", "y", "a",
				"a", "ae", "a", "a", "a", "a", "e", "e", "e", "a", "e", "a",
				"a", "a", "a", "au", "e", "a", "o", "a", "y", "ii", "i", "i",
				"i", "i", "a", "a", "o", "i", "u", "u", "a", "y", "y", "y",
				"ae", "aa", "ae", "ae", "ae", "ae", "a", "ei", "a", "a", "a",
				"a", "i", "a", "a", "a", "e", "a", "a", "a", "a", "a", "a",
				"a", "o", "a", "a", "a", "a", "a", "e", "ei", "e", "e", "a",
				"a", "a", "a", "o", "ii", "u", "u", "u", "ia", "a", "a", "o",
				"y", "o", "ae", "a", "a", "ia", "i", "a", "a", "ii", "y", "o",
				"ae", "e", "ae", "a", "a", "ei", "e", "a", "a", "a", "i", "u",
				"y", "ae", "ae", "a", "a", "a", "a", "a", "a", "ae", "a", "a",
				"ei", "ei", "u", "o", "aa", "ae", "a", "a", "a", "a", "e", "e",
				"e", "e", "e", "e", "oa", "o", "oo", "o", "o", "o", "ae", "i",
				"y", "y", "y", "y", "y", "a", "o", "a", "a", "a", "e", "y",
				"o", "a", "a", "a", "a", "a", "e", "o", };
		String demoStartConsonants[] = { "ab", "ab", "ad", "ad", "adr", "ad",
				"aelr", "aer", "aermh", "aes", "aes", "af", "ag", "agl",
				"aithl", "aj", "akh", "akk", "al", "alb", "al", "all", "al",
				"al", "alth", "amr", "an", "and", "andr", "anf", "anl", "aol",
				"aq", "ar", "ar", "ar", "arb", "ardr", "ardr", "arg", "arkh",
				"ark", "arl", "ar", "asc", "atht", "aubr", "aubr", "aul",
				"aul", "aum", "aumr", "av", "b", "b", "b", "b", "b", "b", "b",
				"bh", "b", "b", "br", "br", "b", "c", "ch", "ch", "ch", "ch",
				"ch", "cl", "cl", "c", "c", "c", "c", "c", "c", "c", "d", "d",
				"d", "d", "d", "d", "d", "d", "d", "d", "dh", "d", "dr", "dr",
				"dr", "d", "d", "d", "ear", "ed", "edw", "ed", "ehl", "ehr",
				"eil", "el", "el", "el", "el", "el", "elb", "elb", "eld",
				"eld", "eldr", "el", "el", "elh", "el", "el", "elkh", "ell",
				"el", "el", "elp", "elt", "elt", "emm", "entr", "er", "ergl",
				"er", "erl", "erl", "er", "er", "esch", "est", "ethl", "ettr",
				"ev", "eyr", "f", "f", "f", "f", "f", "f", "f", "f", "ffl",
				"fh", "fh", "f", "f", "f", "fl", "fl", "f", "f", "g", "g", "g",
				"g", "g", "g", "g", "g", "g", "g", "g", "gl", "gl", "g", "gr",
				"h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h", "h",
				"h", "h", "h", "h", "h", "h", "h", "ief", "iev", "ih", "ilbr",
				"ill", "il", "il", "il", "ill", "ill", "ilph", "ilr", "ilth",
				"il", "inch", "in", "injr", "int", "iol", "iolr", "ith",
				"ithr", "ivl", "ivr", "iymbr", "iyr", "iyr", "j", "j", "j",
				"j", "jh", "jh", "jh", "jh", "jh", "jh", "j", "j", "j", "j",
				"j", "k", "k", "k", "k", "k", "k", "k", "k", "k", "k", "kh",
				"kh", "kh", "kh", "kh", "kh", "kh", "kh", "kh", "k", "k", "k",
				"kl", "k", "k", "kr", "k", "k", "k", "k", "k", "l", "l", "l",
				"l", "l", "l", "l", "l", "l", "l", "l", "lh", "lh", "l", "ll",
				"ll", "ll", "l", "l", "l", "l", "l", "l", "l", "m", "m", "m",
				"m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "m", "mh",
				"m", "m", "m", "m", "m", "ml", "ml", "m", "m", "m", "m", "m",
				"m", "m", "m", "m", "m", "m", "m", "n", "n", "n", "n", "n",
				"n", "n", "n", "n", "n", "n", "n", "nh", "n", "n", "n", "nl",
				"n", "n", "nr", "n", "n", "n", "n", "n", "oac", "oen", "ohmbr",
				"ol", "ol", "ol", "on", "onc", "ond", "ondr", "onv", "or",
				"orlp", "ornd", "ornth", "ornth", "or", "osl", "ot", "ot",
				"oth", "p", "p", "p", "p", "ph", "ph", "phr", "p", "pl", "p",
				"p", "p", "p", "q", "q", "q", "r", "r", "r", "r", "r", "r",
				"r", "r", "r", "r", "r", "r", "r", "rh", "rh", "rh", "rh",
				"rh", "rh", "rh", "r", "r", "r", "r", "r", "r", "r", "r", "r",
				"r", "r", "r", "r", "r", "r", "s", "s", "s", "s", "s", "s",
				"s", "s", "s", "sh", "sh", "sh", "sh", "sh", "sh", "sh", "sh",
				"s", "s", "s", "s", "sk", "s", "sr", "str", "s", "s", "s", "s",
				"s", "t", "t", "t", "t", "t", "t", "t", "t", "t", "t", "t",
				"t", "t", "t", "t", "t", "t", "t", "t", "t", "t", "t", "t",
				"t", "t", "t", "th", "th", "th", "th", "th", "th", "t", "tl",
				"t", "t", "t", "tr", "tr", "tr", "tr", "ts", "ts", "t", "s",
				"s", "s", "s", "sh", "sk", "s", "s", "s", "t", "t", "t", "t",
				"t", "t", "tr", "ual", "uev", "uldr", "uldr", "urdd", "us",
				"uth", "v", "v", "v", "v", "v", "v", "v", "v", "v", "v", "vh",
				"vh", "vh", "v", "v", "w", "w", "w", "w", "w", "w", "w", "w",
				"x", "x", "xh", "xh", "xh", "yal", "yesch", "yh", "yl", "ynl",
				"z", "z", "z", "z", "z", "z", "zh", "z", };
		String demoEndConsonants[] = { "r", "m", "r", "ll", "s", "nd", "nd",
				"mr", "nth", "lbh", "b", "r", "nd", "n", "sr", "d", "r", "ll",
				"r", "th", "l", "l", "v", "ndr", "v", "l", "th", "th", "n",
				"r", "rd", "lc", "r", "thr", "l", "n", "ldr", "ll", "lstr",
				"l", "r", "nd", "f", "nd", "l", "nd", "tt", "rw", "m", "r",
				"lm", "th", "ngl", "zz", "st", "ln", "h", "r", "hn", "n", "nn",
				"rn", "r", "mb", "st", "l", "k", "nn", "r", "tr", "rc", "ss",
				"rf", "rthor", "d", "ldr", "lm", "ls", "r", "l", "v", "s",
				"nn", "nd", "rl", "r", "th", "ffr", "nsp", "ns", "nd", "v",
				"th", "nd", "nj", "sh", "th", "r", "nsh", "ph", "rd", "c", "d",
				"z", "s", "rf", "nd", "rsh", "rgr", "d", "ndr", "l", "d", "th",
				"l", "ll", "l", "nd", "hr", "l", "l", "r", "nd", "l", "r", "l",
				"n", "rn", "c", "l", "r", "lv", "nd", "lv", "r", "rdr", "n",
				"xf", "ls", "l", "l", "l", "r", "l", "l", "th", "n", "m", "nt",
				"rr", "r", "nn", "lv", "r", "r", "nd", "r", "n", "thg", "l",
				"ch", "m", "lad", "v", "laf", "r", "l", "m", "ldr", "th",
				"lfl", "lg", "nd", "lp", "r", "l", "l", "r", "st", "th", "r",
				"fl", "n", "cc", "r", "b", "mbr", "sk", "n", "m", "t", "ph",
				"th", "r", "th", "tr", "r", "ndr", "th", "l", "v", "d", "s",
				"ndr", "klaun", "v", "nd", "nn", "l", "n", "ss", "rt", "r",
				"r", "r", "v", "n", "n", "r", "ld", "s", "d", "pp", "hv", "l",
				"r", "t", "t", "leth", "r", "lvh", "nd", "r", "r", "sef", "h",
				"l", "nd", "r", "t", "d", "r", "ls", "m", "ss", "ndr", "v",
				"ss", "lv", "rr", "g", "l", "rn", "sk", "sk", "m", "rt", "r",
				"far", "ll", "mr", "r", "ng", "rr", "sh", "thl", "r", "n", "d",
				"j", "mb", "r", "nth", "well", "n", "mb", "rs", "rl", "th",
				"v", "kl", "s", "nth", "nd", "ll", "r", "dd", "r", "lg", "rd",
				"r", "k", "rl", "v", "l", "ndr", "lis", "nd", "r", "ll", "r",
				"th", "n", "h", "ng", "l", "th", "rph", "rth", "rth", "rtl",
				"l", "n", "l", "nt", "g", "rg", "rth", "thr", "rdd", "r", "r",
				"ronth", "l", "th", "nth", "r", "nd", "r", "nd", "pr", "l",
				"rb", "rd", "l", "r", "l", "r", "ld", "ld", "st", "r", "v",
				"m", "sh", "v", "ndr", "nth", "l", "p", "rl", "m", "v", "ls",
				"l", "v", "rl", "ns", "vv", "th", "br", "c", "l", "l", "r",
				"l", "hr", "rh", "r", "r", "r", "ssil", "rr", "l", "r", "nd",
				"r", "rph", "f", "rth", "rd", "rr", "v", "w", "ld", "st", "r",
				"nth", "b", "l", "k", "ln", "th", "n", "r", "th", "m", "v",
				"l", "l", "r", "luv", "th", "nn", "pt", "sp", "l", "ng", "n",
				"l", "sp", "st", "th", "m", "l", "t", "l", "n", "l", "th",
				"th", "l", "h", "m", "th", "v", "v", "v", "ch", "f", "d", "l",
				"v", "kr", "tt", "mbl", "nd", "l", "nl", "lg", "mm", "r", "rl",
				"nd", "v", "r", "n", "ss", "rr", "r", "lv", "m", "m", "n", "l",
				"n", "nt", "nd", "dr", "nd", "m", "lv", "mk", "th", "r", "n",
				"g", "gl", "r", "rnt", "l", "s", "mms", "mn", "ms", "n", "th",
				"nn", "nn", "ns", "r", "n", "r", "n", "r", "th", "r", "r",
				"ssp", "rr", "s", "ss", "r", "th", "hlm", "r", "n", "th", "l",
				"n", "ll", "t", "r", "lth", "rd", "rr", "v", "rsh", "nn", "t",
				"rd", "nn", "r", "l", "v", "r", "nd", "kt", "pp", "lm", "v",
				"ll", "l", "th", "v", "kr", "tt", "v", "r", "r", "l", "n", "n",
				"dr", "th", "r", "n", "r", "nn", "mn", "n", "r", "th", "l",
				"r", "n", "r", "l", "r", "lm", "x", "nd", "rt", "l", "th", "n",
				"sp", "sr", "sst", "d", "rh", "l", "d", "r", "rn", "st", "lch",
				"l", "nd", "qh", "rr", "n", "tt", "rl", "th", "n", "nd", "nd",
				"bb", "lt", "r", "lph", "r", };
		String demofemaleEnd[] = { "adda", "at", "ar", "an", "in", "uce", "el",
				"yl", "ar", "ar", "on", "ail", "is", "ol", "in", "ar", "en",
				"ar", "an", "iel", "ar", "in", "ok", "in", "on", "ynn", "ath",
				"ean", "ath", "en", "yth", "is", "an", "in", "on", "ar", "ane",
				"eth", "yll", "us", "un", "em", "en", "un", "al", "ar", "ic",
				"on", "ar", "ar", "as", "uth", "el", "oam", "yn", "or", "oth",
				"as", "am", "uar", "aar", "ar", "aer", "ern", "arry", "yr",
				"on", "yth", "as", "yrth", "er", "oth", "ach", "ym", "al",
				"all", "ak", "aith", "ym", "iir", "enn", "yor", "ath", "yd",
				"ine", "an", "in", "an", "ach", "uth", "an", "ath", "av", "or",
				"oth", "ar", "an", "il", "os", "ieir", "yr", "yrd", "yrm",
				"ark", "il", "er", "an", "ith", "orr", "ar", "or", "in", "eth",
				"ernth", "ar", "in", "aer", "on", "il", "yr", "on", "el", "ar",
				"ar", "in", "erae", "or", "im", "yth", "al", "iel", "areo",
				"ar", "an", "an", "an", "ith", "us", "ar", "ando", "an", "al",
				"ynnhv", "esc", "ar", "yn", "uil", "ael", "aar", "aern", "ian",
				"ar", "ik", "iin", "ion", "or", "el", "yn", "ar", "ire", "on",
				"eath", "in", "on", "an", "er", "ede", "ar", "ik", "on", "as",
				"ullio", "ald", "al", "yyv", "or", "aari", "aam", "ir", "ar",
				"in", "ar", "en", "ar", "as", "il", "ueth", "ueve", "yk", "os",
				"al", "yl", "ar", "ith", "yr", "yr", "os", "ar", "yn", "aro",
				"ar", "ar", "ath", "or", "an", "as", "une", "yn", "yl", "el",
				"os", "os", "ar", "as", "ath", "am", "es", "ar", "an", "yl",
				"ar", "an", "ar", "or", "os", "in", "an", "ael", "os", "ak",
				"ym", "ik", "as", "ik", "yn", "iah", "ar", "oerm", "ede", "ar",
				"yr", "yl", "an", "el", "ym", "yth", "on", "aan", "is", "ar",
				"ell", "al", "eith", "al", "yrmn", "oun", "oth", "in", "igh",
				"ern", "ar", "ash", "oth", "os", "yn", "yn", "il", "aar",
				"oth", "in", "uil", "osx", "ar", "el", "ul", "athai", "il",
				"as", "ym", "aerth", "is", "orn", "arm", "ar", "aerth", "an",
				"an", "ais", "on", "ari", "or", "ir", "asli", "yn", "yth",
				"al", "ele", "ath", "eiym", "oth", "aur", "ach", "er", "ien",
				"ith", "ild", "al", "yl", "orn", "ys", "al", "al", "ar",
				"ossae", "ym", "ostroi", "or", "an", "il", "ys", "urn", "in",
				"iil", "in", "ar", "ar", "ertho", "am", "am", "eon", "eth",
				"ual", "yn", "yn", "or", "or", "in", "arth", "al", "en", "ol",
				"or", "ossae", "os", "orn", "yn", "ian", "ir", "ian", "ym",
				"as", "enth", "el", "yn", "urae", "er", "ir", "as", "ith",
				"ar", "oth", "yr", "ist", "ar", "il", "as", "as", "ym", "ar",
				"yn", "yn", "ion", "al", "is", "is", "in", "ar", "om", "an",
				"al", "an", "am", "er", "ym", "aln", "or", "arte", "ynn", "ur",
				"yr", "anthae", "or", "al", "il", "yr", "ore", "aun", "el",
				"yn", "ar", "en", "yf", "yl", "yrr", "en", "el", "ir", "ys",
				"ar", "eth", "im", "eloe", "ion", "ardh", "ar", "ith", "il",
				"aen", "en", "yn", "ell", "on", "ul", "ymn", "el", "ars", "ar",
				"evv", "anchai", "ith", "ar", "auth", "el", "ath", "ian",
				"ario", "yl", "ash", "ir", "ik", "ist", "yr", "ar", "aht",
				"is", "ar", "in", "ohm", "yl", "ar", "ar", "alr", "yn", "yth",
				"en", "yn", "al", "ym", "in", "on", "aeuth", "in", "il", "ivh",
				"yll", "il", "yl", "ath", "iel", "edd", "ur", "on", "ar",
				"ion", "aln", "ar", "ist", "yajn", "ir", "il", "an", "yl",
				"an", "an", "yn", "us", "ar", "olthe", "ar", "oss", "iorn",
				"an", "al", "ic", "er", "as", "us", "il", "el", "ars", "il",
				"ian", "is", "aht", "yl", "yn", "an", "ivh", "aeuth", "yl",
				"iel", "olthe", "iorn", "ir", "eth", "yn", "yn", "usk", "aar",
				"im", "yun", "il", "ian", "er", "an", "uil", "ali", "err",
				"yn", "an", "an", "ori", "in", "ar", "on", "as", "ari", "yr",
				"ym", "yn", "elleu", "ael", "an", "alph", "er", "alh", "alth",
				"ion", "il", "ant", "orn", "ar", "eth", "as", "ish", "andro",
				"or", "os", "ar", "on", "ulae", };
		String nameInstructions[] = { "cf", "cvdf", "cvdf", "cvdvdf", "cvdf",
				"cf", "cvdf", "cvdf", "cf", "cf", "cf", "cvdf", "cf", "cvdf",
				"cf", "cvf", "cvdf", "cf", "cvdvdf", "cvdf", "cvdf", "cvf",
				"cf", "cvdf", "cvdf", "cf", "cvdvdf", "cvdf", "cvdf", "cvdf",
				"cf", "cf", "cvdf", "cvdf", "cvdf", "cvdvdf", "cf", "cf", "cf",
				"cf", "cf", "cvf", "cf", "cf", "cf", "cf", "cf", "cf", "cvdf",
				"cvdf", "cvdf", "cvf", "cvdf", "cvdvdf", "cvdvdf", "cvdvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cvdvdf", "cvdvdf", "cvdf",
				"cvf", "cvdf", "cvdvdf", "cvdvdf", "cvdf", "cvdvdf", "cvf",
				"cvdvdf", "cvdf", "cvdvdf", "cvf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvdvdf", "cvdvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdvdf",
				"cvdf", "cvdvdf", "cvdf", "cf", "cvdf", "cvdf", "cvdvdf",
				"cvdf", "cvdf", "cvdf", "cf", "cf", "cf", "cvdf", "cvdf",
				"cvdf", "cvf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvf",
				"cf", "cf", "cvdf", "cvdf", "cvdvdf", "cvdf", "cvf", "cvdf",
				"cvdf", "cvdvdf", "cvdf", "cvf", "cvf", "cvdf", "cf", "cvdf",
				"cvdf", "cf", "cvdvdf", "cf", "cvdf", "cvf", "cvdf", "cvdf",
				"cvdf", "cf", "cvf", "cvdf", "cf", "cvdf", "cvdf", "cvdf",
				"cvdvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cf", "cvdf", "cvdf",
				"cvdvdf", "cvdvdf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvdf", "cvdvdf", "cvdf", "cvdvdf", "cvdvdf", "cvdf",
				"cvdf", "cvdvdf", "cvdf", "cvf", "cvdf", "cvdvdf", "cvdvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cvdvdf", "cvdvdf", "cvdvdf",
				"cvdvdf", "cvdf", "cvdvdf", "cvdvdf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvdvdf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cf", "cf",
				"cvdvdf", "cf", "cvdf", "cvdvdf", "cvdf", "cvdvdf", "cvdf",
				"cvdf", "cf", "cf", "cvdf", "cvdvdf", "cf", "cvdf", "cf",
				"cvdf", "cf", "cf", "cf", "cvdf", "cvdf", "cf", "cf", "cvdf",
				"cvdvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvf", "cvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdvdf",
				"cvdvdf", "cvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cvdvdf", "cvdvdf", "cvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cf", "cvdf", "cvdf",
				"cvdvdf", "cvf", "cvf", "cvdf", "cvdvdf", "cvdf", "cvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdvdf", "cvdf",
				"cvf", "cvdvdf", "cvdf", "cvdf", "cf", "cvdvdf", "cvdvdf",
				"cvdf", "cvdf", "cvdf", "cvdf", "cf", "cvdvdf", "cvdf", "cvdf",
				"cvdf", "cvdf", "cvdf", "cvf", "cvdf", "cvdvdf", "cvf",
				"cvdvdf", "cvdvdf", "cvdf", "cvf", "cvdf", "cvdf", "cvdvdf",
				"cvdvdf", "cvdvdf", "cvdvdf", "cvdvdf", "cvdf", "cvdf", "cvdf",
				"cvdvdf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cf",
				"cvdvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cvf",
				"cvdf", "cvdf", "cvdf", "cvdvdf", "cvdvdf", "cvf", "cvdvdf",
				"cvdvdf", "cvdvdf", "cvdf", "cvdf", "cvdvdf", "cvdvdf", "cvdf",
				"cvdf", "cvdvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdvdf",
				"cf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cf",
				"cvdvdf", "cf", "cf", "cf", "cvf", "cvdvdf", "cvdf", "cf",
				"cf", "cvdf", "cf", "cf", "cf", "cf", "cvdf", "cvdf", "cvdf",
				"cf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvdvdf", "cvdvdf", "cvdf", "cvdf", "cvf", "cvdf", "cvdf",
				"cvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cvf",
				"cvdvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdvdf", "cvdvdf",
				"cvdvdf", "cvdvdf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvdvdf", "cvdf", "cvdf", "cvdvdf", "cf", "cvdvdf",
				"cvdvdf", "cvdf", "cvdf", "cvdvdf", "cvf", "cvdf", "cvf",
				"cvdvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvf",
				"cvdvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvf", "cvf",
				"cvdvdf", "cvdf", "cvf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvdvdf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cvdvdf", "cvdf",
				"cvdvdf", "cvdf", "cvdf", "cf", "cvdf", "cvdvdf", "cvdf",
				"cvdf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvdvdf", "cvdf", "cvdf", "cvdf", "cvdvdf", "cvdf", "cvdf",
				"cvdvdf", "cvdf", "cvdvdf", "cvdvdf", "cvdf", "cvdvdf", "cvdf",
				"cvdf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvdvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdvdf", "cvdf",
				"cvdvdf", "cf", "cvdvdf", "cvdf", "cvdf", "cvdvdf", "cvdf",
				"cvdvdf", "cvf", "cvdf", "cvdvdf", "cvdvdf", "cvdf", "cvdvdf",
				"cvdvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdvdf", "cvdvdf",
				"cvdf", "cvdf", "cvdf", "cvdvdf", "cf", "cvdf", "cvf", "cvdf",
				"cvf", "cvf", "cf", "cvdf", "cvdf", "cvdf", "cvdf", "cvdvdf",
				"cvdf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvf", "cvdf", "cvdvdf", "cvdf", "cvdf", "cvdf",
				"cvdf", "cvdf", "cf", "cvdf", "cvdf", "cvdf", "cf", "cvdvdf",
				"cf", "cf", "cvdf", "cvdvdf", "cf", "cvdf", "cvdf", "cvf",
				"cvdf", "cvdvdf", "cf", "cvf", "cvf", "cvdf", "cvdf", "cf", };

		this.vocals.addAll(Arrays.asList(demoVocals));
		this.startConsonants.addAll(Arrays.asList(demoStartConsonants));
		this.endConsonants.addAll(Arrays.asList(demoEndConsonants));
		this.nameInstructions.addAll(Arrays.asList(nameInstructions));
		this.femaleEnd.addAll(Arrays.asList(demofemaleEnd));
	}
}
